# Defines a default set of lint rules enforced for projects at Google. For
# details and rationale, see
# https://github.com/dart-lang/pedantic#enabled-lints.

include: package:very_good_analysis/analysis_options.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.

# Uncomment to specify additional rules.
linter:
  rules:
    sort_constructors_first : false
    avoid_print : false
    cascade_invocations : false

# analyzer:
#   exclude:
#     - path/to/excluded/files/**
