name: dart_operators
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0
dev_dependencies:
  very_good_analysis: ^2.1.2
dependencies:
  equatable: ^2.0.3
